### GET all users (LOCAL)

GET http://localhost:3000/users

### GET all users (RENDER)

GET https://project1-bu18.onrender.com/users

### GET user by Id (LOCAL)

GET http://localhost:3000/users/6a072c62c289b09dd3d070eb

### GET user by Id (RENDER)

GET https://project1-bu18.onrender.com/users/6a072c62c289b09dd3d070eb

### Create a new user (LOCAL)

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

  {
    "firstName": "George",
    "lastName": "White",
    "email": "george@example.com",
    "favoriteColor": "Silver",
    "birthday": "12/08"
  }

### Create a new user (RENDER)

POST https://project1-bu18.onrender.com/users HTTP/1.1
content-type: application/json

  {
    "firstName": "George",
    "lastName": "White",
    "email": "george@example.com",
    "favoriteColor": "Silver",
    "birthday": "12/08"
  }

### PUT user (LOCAL)

PUT http://localhost:3000/users/6a0b61bef240a068f856daba HTTP/1.1
content-type: application/json

  {
    "firstName": "George",
    "lastName": "White",
    "email": "test1@example.com",
    "favoriteColor": "Silver",
    "birthday": "12/08"
  }

### PUT user (RENDER)

PUT https://project1-bu18.onrender.com/users/6a0b61bef240a068f856daba HTTP/1.1
content-type: application/json

  {
    "firstName": "George",
    "lastName": "White",
    "email": "test1@example.com",
    "favoriteColor": "Silver",
    "birthday": "12/08"
  }

### DELETE user (LOCAL)

DELETE http://localhost:3000/users/6a0b61bef240a068f856daba HTTP/1.1

### DELETE user (RENDER)

DELETE https://project1-bu18.onrender.com/users/6a072c62c289b09dd3d070eb HTTP/1.1